<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net8.0-windows</TargetFramework>
    <StartupObject>Inventor_Tools.My.MyApplication</StartupObject>
    <UseWindowsForms>true</UseWindowsForms>
    <MyType>WindowsForms</MyType>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="OldCode\CopyToolFunctions.vb" />
    <Compile Remove="OldCode\InventorFunctions.vb" />
    <Compile Remove="OldCode\InvtAssemblyObj.vb" />
    <Compile Remove="OldCode\InvtComponentObj.vb" />
    <Compile Remove="OldCode\OldFunctions.vb" />
  </ItemGroup>

  <ItemGroup>
    <Import Include="System.Data" />
    <Import Include="System.Drawing" />
    <Import Include="System.Windows.Forms" />
  </ItemGroup>

  <ItemGroup>
    <None Include="OldCode\CopyToolFunctions.vb" />
    <None Include="OldCode\InventorFunctions.vb" />
    <None Include="OldCode\InvtAssemblyObj.vb" />
    <None Include="OldCode\InvtComponentObj.vb" />
    <None Include="OldCode\OldFunctions.vb" />
  </ItemGroup>

  <ItemGroup>
    <Reference Include="Autodesk.Inventor.Interop">
      <HintPath>..\..\..\..\..\..\Program Files\Autodesk\Inventor 2026\Bin\Autodesk.Inventor.Interop.dll</HintPath>
    </Reference>
  </ItemGroup>

  <ItemGroup>
    <Compile Update="My Project\Application.Designer.vb">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Application.myapp</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <None Update="My Project\Application.myapp">
      <Generator>MyApplicationCodeGenerator</Generator>
      <LastGenOutput>Application.Designer.vb</LastGenOutput>
    </None>
  </ItemGroup>

  <ItemGroup>
    <Folder Include="LogFiles\" />
  </ItemGroup>

</Project>